baseURL = "http://localhost:1313/"
languageCode = "en-us"
theme = ["hugo-theme-chunky-poster"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  description = "Computers according to Sathvik"
  homepageImage = "/images/coder.png"
  share = true
  showLanguageSwitcher = false

  [params.prismJS]
    enable = false
    theme = "okaidia"

[markup]
  [markup.highlight]
    codeFences = false